config/routes.rb
Logfiles::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "site/index"
  get "site/uptime"
  
    resources :nodes do
      resources :line_items
      resources :logs
    end

  root :to => 'site#index', :as => "site"

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :line_items, :dependent => :destroy
  
  def delete_log_from_node(node)
    node.line_items.each do |item|
      if item.log_id != nil
        log = Log.find(item.log_id)
        log.destroy
      end
    end
  end
  
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to nodes_path, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to nodes_path, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.delete_log_from_node(@node)
    @node.destroy
    
    

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 20 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => "5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h2>Listing nodes</h2>
<br/>
  <div class="input-prepend">
    <%= link_to 'New Node', new_node_path, :class => "btn" %>
  </div>
<br/>
<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
	<th>Logs Count</th>
    <th>Confin</th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= link_to node.name, node_line_items_path(:node_id => node) %></td>
    <td><%= node.description %></td>
	<td><%= node.line_items.count %></td>
    <td>
	<%= link_to 'Show', node_line_items_path(:node_id => node) %> |
    <%= link_to 'Edit', edit_node_path(node) %> |
    <%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Description:</b>
  <%= @node.description %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>