config/routes.rb
Logfiles::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "site/index"
  get "site/uptime"
  
    resources :nodes do
      resources :line_items
      resources :logs
    end

  root :to => 'site#index', :as => "site"

end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :cron_time, :file_size, :filepath, :operate_type, :reserve_dates, :title, :recurse, :file_time
  has_many :line_items
  
  OPERATE_TYPES = [["RM",0], ["Archive",1], ["Cat null",2]]
  RECURSE_TYPES = [["path",0], ["path/*",1], ["path/*/*",2],["path/**/*",3]]
  FILETIME_TYPES = [["ctime",0],["mtime",1],["atime",2]]
  
  validates_presence_of :title, :filepath, :on => :create, :message => "can't be blank"
  validates :file_size, :format => {
    :with => /^$|(\d+b|k|m|g|t)/i,
    :message => "file size value error !"
  }
  validates :reserve_dates, :format => {
    :with => /(\d+h|d|w)/i,
    :message => "Input file age value error !"
  }
  
  def add_line_item_from_log(node,log)
    line_items.build(:node_id => node, :log_id => log)
  end
  
  def delete_line_item_from_log(log)
    line_item = line_items.find_by_log_id(log)
    line_item.destroy
  end
      
  
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @node = current_node
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @node = current_node
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @node = current_node
    @log = Log.new(params[:log])
    
    @log.add_line_item_from_log(params[:node_id],@log)    
    respond_to do |format|
      if @log.save
        format.html { redirect_to node_line_items_path, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to node_line_items_path, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    @log.delete_line_item_from_log(params[:id])

    respond_to do |format|
      format.html { redirect_to node_line_items_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<div>
<%= form_for [@node, @log], :class => "form-horizontal" do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>
      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
	<label>Matches</label>
	<div class="controls">
    	<%= f.text_field :title %>
		<span class="help-block">Example *.log app[/\d+/].tmp, Values separated by spaces.</span>
	</div>
  </div>
  <div class="control-group">
    <label>File Path</label>
    <%= f.text_field :filepath %>
  </div>
  <div class="control-group">
	<label>Recurse</label>
	<%= f.select :recurse, Log::RECURSE_TYPES, :selected => 0 %>
  </div>
  <div class="control-group">
	<label>File Time</label>
	<%= f.select :file_time, Log::FILETIME_TYPES, :selected => 1 %>
  </div>
  <div class="control-group">
	<lable>Operate Type</label><br>
	<%= f.select :operate_type, Log::OPERATE_TYPES, :selected=> 0 %>
  </div>
  <br/>
  <div class="input-append">
    <label>File Size</label>
    <%= f.text_field :file_size, :placeholder=>"Input values or empty"%>
	<span class="help-block">Example 10b(byte), 10k(KB), 10m(MB), 10g(GB), 10t(TB)</span>
  </div>
  
  <div class="input-prepend">
    <label>File Age</label>
    <%= f.text_field :reserve_dates, :value => "1w" %>
	<span class="help-block">Example 3h(hours), 2d(days), 1w(weeks)</span>
  </div>
  <div class="control-group">
    <label>Cron</label>
    <%= f.time_select :cron_time, :include_blank => true, :width => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/logs/edit.html.erb
<h3>Editing log</h3>

<%= render 'form' %>

<%= link_to 'Back', node_line_items_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Filepath</th>
    <th>File size</th>
    <th>Operate type</th>
    <th>Reserve dates</th>
    <th>Cron time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.title %></td>
    <td><%= log.filepath %></td>
    <td><%= log.file_size %></td>
    <td><%= log.operate_type %></td>
    <td><%= log.reserve_dates %></td>
    <td><%= log.cron_time %></td>
  </tr>
<% end %>
</table>

app/views/logs/new.html.erb
<h3>Add Log</h3>

<%= render 'form' %>

<%= link_to 'Back', node_line_items_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @log.title %>
</p>

<p>
  <b>Filepath:</b>
  <%= @log.filepath %>
</p>

<p>
  <b>File size:</b>
  <%= @log.file_size %>
</p>

<p>
  <b>Operate type:</b>
  <%= @log.operate_type %>
</p>

<p>
  <b>Reserve dates:</b>
  <%= @log.reserve_dates %>
</p>

<p>
  <b>Cron time:</b>
  <%= @log.cron_time %>
</p>


<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>