config/routes.rb
Logfiles::Application.routes.draw do
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "site/index"
  get "site/uptime"
  
    resources :nodes do
      resources :line_items
      resources :logs
    end

  root :to => 'site#index', :as => "site"

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :log_id, :node_id
  belongs_to :node
  belongs_to :log
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    #@line_items = LineItem.all
    @node = current_node
    @line_items = current_node.line_items
    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @line_items }
      format.json
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(params[:line_item])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to node_line_items_path, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node_id %><br />
    <%= f.number_field :node_id %>
  </div>
  <div class="field">
    <%= f.label :log_id %><br />
    <%= f.number_field :log_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h2>Listing Node Logs</h2>

<br/>
<h3><%= @node.name %></h3>
<div class="input-prepend">
	<%= link_to 'New Log', new_node_log_path, :class => "btn" %>
	<%= link_to "Back", nodes_path, :class => "btn" %>
</div>


<table class="table table-hover"> 
  <tr>
    <th>Matches</th>
    <th>Log path</th>
    <th>Operate Type</th>
    <th>File Age</th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>  
    <td><%= line_item.log.title %></td>
	<td><%= line_item.log.filepath %></td>
	<td><%= case line_item.log.operate_type when 0; "RM" when 1; "Archive" when 2; "Cat null" end %></td>
	<td><%= line_item.log.reserve_dates %></td>
	<td><%= link_to "Edit", edit_node_log_path(:id => line_item.log_id) %> | 
		<%= link_to "Destroy", node_log_path(:id => line_item.log_id ) ,method: :delete, data: { confirm: 'Are you sure?' }%>
  </tr>
<% end %>
</table>

app/views/line_items/index.json.erb
{
  id: "<%= @node.name %>",
  <% @line_items.each do |line_item| %>
  "<%= line_item.log.title %>": {
      "file_path": "<%= line_item.log.filepath %>",
      "file_size": "<%= line_item.log.file_size %>",
      "operate_type": "<%= line_item.log.operate_type %>",
      "dates": "<%= line_item.log.reserve_dates || "0" %>"
	},
	<% end %>
}

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node:</b>
  <%= @line_item.node_id %>
</p>

<p>
  <b>Log:</b>
  <%= @line_item.log_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>